CREATE TABLE IF NOT EXISTS `he-dev-data.dev_data_landing.iafas_mdm_siniestro_dif2` (
  id_siniestro STRING,
  id_origen STRING,
  id_siniestro_origen STRING,
  id_poliza STRING,
  id_contratante STRING,
  id_producto STRING,
  id_certificado STRING,
  id_titular STRING,
  fec_hora_ocurrencia TIMESTAMP,
  fec_notificacion TIMESTAMP,
  num_siniestro STRING,
  fec_operacion TIMESTAMP,
  id_estado_siniestro_origen STRING,
  des_estado_siniestro_origen STRING,
  id_estado_siniestro STRING,
  des_estado_siniestro STRING,
  fec_estado TIMESTAMP,
  id_ubicacion_geografica STRING,
  des_departamento_siniestro STRING,
  des_provincia_siniestro STRING,
  des_distrito_siniestro STRING,
  des_ubicacion_detallada STRING,
  id_unidad_asegurable STRING,
  id_asegurado STRING,
  des_unidad_asegurable STRING,
  sexo_asegurable STRING,
  fec_nacimiento_asegurable DATE,
  num_documento_asegurable STRING,
  tip_documento_asegurable STRING,
  rango_etareo_asegurable STRING,
  fec_constitucion_siniestro TIMESTAMP,
  fec_anulacion TIMESTAMP,
  fec_ult_liquidacion TIMESTAMP,
  mto_total_reserva NUMERIC,
  mto_total_reserva_usd NUMERIC,
  mto_total_reserva_ajustador NUMERIC,
  mto_total_reserva_usd_ajustador NUMERIC,
  mto_total_aprobado NUMERIC,
  mto_total_aprobado_usd NUMERIC,
  mto_aprobado_deduci NUMERIC,
  mto_aprobado_deduci_usd NUMERIC,
  mto_total_facturado NUMERIC,
  mto_total_pendiente NUMERIC,
  mto_total_pendiente_usd NUMERIC,
  mto_total_pagado NUMERIC,
  mto_total_pagado_usd NUMERIC,
  mto_total_pagado_ajustador NUMERIC,
  mto_total_pagado_usd_ajustador NUMERIC,
  mto_pagado_deduci NUMERIC
)
PARTITION BY TIMESTAMP_TRUNC(fec_hora_ocurrencia, MONTH);


