CREATE TABLE `DATA_FLOW_CONFIG` (
     `ID` varchar(100) COLLATE utf8mb4_general_ci NOT NULL, 
     `PROJECT_ID` varchar(100) COLLATE utf8mb4_general_ci NOT NULL, 
     `VALIDATION_FILE_ID` varchar(100) COLLATE utf8mb4_general_ci NOT NULL, 
     `HOMOLOGATION_FILE_ID` varchar(100) COLLATE utf8mb4_general_ci NOT NULL, 
     `WORKFLOW_NAME` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `WORKFLOW_DESCRIPTION` varchar(5000) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `ORIGIN_COMPANY` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `ORIGIN_FORMAT` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `ORIGIN_TYPE` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `ORIGIN_EXTENSION` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `ORIGIN_LINK_FILE` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `DESTINATION_BUCKET` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `DESTINATION_DIRECTORY` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `DESTINATION_FILE_NAME` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `DESTINATION_BG_NAME` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `DESTINATION_DSET_LANDING` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `DESTINATION_TABLE_LANDING` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `COMPOSER_NAME` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `DAG_STORAGE_DSET_NAME` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `SQL_SCRIPT` varchar(5000) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `DESTINATION_DSET_UNIVERSAL` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `DESTINATION_TABLE_UNIVERSAL` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `ARCHIVE_DIRECTORY` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL, 
     `DESTINATION_BUCKET_HIST` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL, PRIMARY KEY (`ID`), UNIQUE KEY `UNIQUE_ID` (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci