CREATE TABLE `DATA_FLOW_CONFIG` ( 
    `ID` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Identificador de proceso de carga parquet a BQ', 
    `PROJECT_ID` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Identificador de proyecto', 
    `VALIDATION_FILE_ID` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Identificador de validación', 
    `HOMOLOGATION_FILE_ID` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Identificador de homologación', 
    `WORKFLOW_NAME` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Nombre del Proceso', 
    `WORKFLOW_DESCRIPTION` varchar(5000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Descripcion detallada del Proceso', 
    `ORIGIN_COMPANY` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Compañia de donde provienen los datos', 
    `ORIGIN_FORMAT` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Formato de origen de datos', 
    `ORIGIN_TYPE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Tipo de formato de archivo', 
    `ORIGIN_EXTENSION` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Extension de archivo', 
    `ORIGIN_LINK_FILE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Link de origen de archivo', 
    `DESTINATION_BUCKET` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Nombre Bucket origen', 
    `DESTINATION_DIRECTORY` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Directorio del archivo', 
    `DESTINATION_FILE_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Nombre de archivo origen', 
    `DESTINATION_BG_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Nombre de proyecto donde esta la tabla landing', 
    `DESTINATION_DSET_LANDING` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Nombre del dataset en landing', 
    `DESTINATION_TABLE_LANDING` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Nombre de la tabla en landing', 
    `COMPOSER_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Nombre del enviroment del composer', 
    `DAG_STORAGE_DSET_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Identificador del dag a ejecutar', 
    `SQL_SCRIPT` varchar(5000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Script de creacion de tabla', 
    `DESTINATION_DSET_UNIVERSAL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Nombre del dataset en Universal', 
    `DESTINATION_TABLE_UNIVERSAL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Nombre de la tabla en Universal', 
    `ARCHIVE_DIRECTORY` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Ruta de archivos historicos procesados', 
    `DESTINATION_BUCKET_HIST` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Nombre del bucket de archivos historicos', PRIMARY KEY (`ID`), UNIQUE KEY `UNIQUE_ID` (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci