INSERT INTO `db-compass`.`DATA_FLOW_CONFIG` (
    ID,
    PROJECT_ID,
    VALIDATION_FILE_ID,
    HOMOLOGATION_FILE_ID,
    WORKFLOW_NAME,
    WORKFLOW_DESCRIPTION,
    ORIGIN_COMPANY,
    ORIGIN_FORMAT,
    ORIGIN_TYPE,
    ORIGIN_EXTENSION,
    ORIGIN_LINK_FILE,
    DESTINATION_BUCKET,
    DESTINATION_DIRECTORY,
    DESTINATION_FILE_NAME,
    DESTINATION_BG_NAME,
    DESTINATION_DSET_LANDING,
    DESTINATION_TABLE_LANDING,
    COMPOSER_NAME,
    DAG_STORAGE_DSET_NAME,
    SQL_SCRIPT,
    DESTINATION_DSET_UNIVERSAL,
    DESTINATION_TABLE_UNIVERSAL,
    ARCHIVE_DIRECTORY,
    DESTINATION_BUCKET_HIST
) VALUES (
    'a379e9be-14fe-4914-9321-76dc32f5b233',
    'he-dev-data',
    '338c2e50-1bc2-4b13-9145-95190a55e53d',
    'd490efdc-0448-468d-97e4-749de76399e3',
    'Ingesta Tabla',
    'Trae la informacion de Rimac hacia Compas',
    'RIMAC',
    'ARCHIVO',
    'PARQUET',
    '.parquet',
    'File',
    'he-dev-data',
    'he-dev-data-ipress/ipress_clinicas/internacional/',
    'siniestro2',
    'he-dev-data',
    'dev_data_landing',
    'iafas_mdm_siniestro2',
    'dev_airflow_data',
    'dev_dag_siniestros_parquet_GCS_BQ_GCS',
    'CREATE TABLE IF NOT EXISTS `he-dev-data.dev_data_landing.iafas_mdm_siniestro` ( id_siniestro STRING, tip_ingreso_siniestro NUMERIC, tip_reclamo STRING, des_tipo_reclamo STRING, num_obligacion STRING, tip_procedencia STRING, ind_tedef_salud STRING, fec_hora_ocurrencia TIMESTAMP, fec_ult_liquidacion TIMESTAMP, fec_notificacion TIMESTAMP, fec_operacion TIMESTAMP, mnt_gasto_total_con_igv NUMERIC, nro_nota_credito STRING, mnt_nota_credito NUMERIC, mnt_planilla_afiliado_usd NUMERIC, mnt_planilla_afiliado_sol NUMERIC, mnt_observado NUMERIC, id_persona_proveedor_siniestro STRING, tip_documento_proveedor_siniestro STRING, num_documento_proveedor_siniestro STRING, nom_completo_proveedor_siniestro STRING, dir_proveedor_siniestro STRING, cod_sede_proveedor_siniestro STRING, nom_sede_proveedor_siniestro STRING, dir_sede_proveedor_siniestro STRING, id_persona_afiliado STRING, tip_documento_afiliado STRING, num_documento_afiliado STRING, nom_completo_afiliado STRING, fec_nacimiento_afiliado DATE, edad_afiliado NUMERIC, edad_afiliado_ocurrencia NUMERIC, des_sexo_afiliado STRING, est_cambios STRING )',
    'he-dev-data-ipress/ipress_clinicas/internacional/Inventario_siniestros/',
    'he-dev-data-historicos'
);

INSERT INTO `db-compass`.`DATA_FLOW_CONFIG` (
    ID,
    PROJECT_ID,
    VALIDATION_FILE_ID,
    HOMOLOGATION_FILE_ID,
    WORKFLOW_NAME,
    WORKFLOW_DESCRIPTION,
    ORIGIN_COMPANY,
    ORIGIN_FORMAT,
    ORIGIN_TYPE,
    ORIGIN_EXTENSION,
    ORIGIN_LINK_FILE,
    DESTINATION_BUCKET,
    DESTINATION_DIRECTORY,
    DESTINATION_FILE_NAME,
    DESTINATION_BG_NAME,
    DESTINATION_DSET_LANDING,
    DESTINATION_TABLE_LANDING,
    COMPOSER_NAME,
    DAG_STORAGE_DSET_NAME,
    SQL_SCRIPT,
    DESTINATION_DSET_UNIVERSAL,
    DESTINATION_TABLE_UNIVERSAL,
    ARCHIVE_DIRECTORY,
    DESTINATION_BUCKET_HIST
) VALUES (
    'd10532fa-3222-47c9-a5b4-faf62b842a11',
    'he-dev-data',
    '338c2e50-1bc2-4b13-9145-95190a55e53d',
    'd490efdc-0448-468d-97e4-749de76399e3',
    'Ingesta Siniestros',
    'Trae la informacion de Rimac hacia Compas',
    'RIMAC',
    'ARCHIVO',
    'PARQUET',
    '.parquet',
    'File',
    'he-dev-data',
    'he-dev-data-ipress/ipress_clinicas/internacional/',
    'siniestro',
    'he-dev-data',
    'dev_data_landing',
    'iafas_mdm_siniestro',
    'dev_airflow_data',
    'dev_dag_siniestros_parquet_GCS_BQ_GCS',
    'CREATE TABLE IF NOT EXISTS `he-dev-data.dev_data_landing.iafas_mdm_siniestro` ( id_siniestro STRING, tip_ingreso_siniestro NUMERIC, tip_reclamo STRING, des_tipo_reclamo STRING, num_obligacion STRING, tip_procedencia STRING, ind_tedef_salud STRING, fec_hora_ocurrencia TIMESTAMP, fec_ult_liquidacion TIMESTAMP, fec_notificacion TIMESTAMP, fec_operacion TIMESTAMP, mnt_gasto_total_con_igv NUMERIC, nro_nota_credito STRING, mnt_nota_credito NUMERIC, mnt_planilla_afiliado_usd NUMERIC, mnt_planilla_afiliado_sol NUMERIC, mnt_observado NUMERIC, id_persona_proveedor_siniestro STRING, tip_documento_proveedor_siniestro STRING, num_documento_proveedor_siniestro STRING, nom_completo_proveedor_siniestro STRING, dir_proveedor_siniestro STRING, cod_sede_proveedor_siniestro STRING, nom_sede_proveedor_siniestro STRING, dir_sede_proveedor_siniestro STRING, id_persona_afiliado STRING, tip_documento_afiliado STRING, num_documento_afiliado STRING, nom_completo_afiliado STRING, fec_nacimiento_afiliado DATE, edad_afiliado NUMERIC, edad_afiliado_ocurrencia NUMERIC, des_sexo_afiliado STRING, est_cambios STRING )',
    'dev_data_analytics',
    'anl_tmp_part_month_siniestro_t2',
    'he-dev-data-ipress/ipress_clinicas/internacional/Inventario_siniestros/',
    'he-dev-data-historicos'
);
